README.md

First README.md revision

---

.github/dependabot.yml
Cargo.lock
Cargo.lock.license
Cargo.toml
README.md
src/error.rs
src/lib.rs
src/main.rs
src/telemetry/hardwareinfo.rs
src/telemetry/mod.rs
src/telemetry/osinfo.rs
src/telemetry/systemstatus.rs

Add initial telemetry implementation
Closes #7 #8 #13

Add initial telemetry implementation

---

.github/workflows/codecov.yaml

Add support to code coverage report upload on github workflow

Add code coverage GitHub workflow

---

.github/workflows/build.yaml
src/main.rs
src/wrapper/systemd.rs

Enable `systemd` feature in the CI build

Fix systemd build

---

src/e2e_test/e2e_test.rs
src/lib.rs

1. 43c7064
2. 13d1e8f
3. d63401b

Fix tests coming from latest merge request

---

.github/workflows/build.yaml
.github/workflows/codecov.yaml
.github/workflows/e2e-test.yaml
Cargo.lock
Cargo.toml
README.md
doc/os_requirements.md
src/lib.rs
src/telemetry/mod.rs
src/telemetry/net_if_properties.rs

Add support to `io.edgehog.devicemanager.NetworkInterfaceProperties`
Close #22

Implement NetworkInterfaceProperties

---

.github/workflows/build.yaml
.github/workflows/codecov.yaml
.github/workflows/e2e-test.yaml

Fix broken CI caused by missing `apt update`

Fix broken CI

---

.reuse/dep5
CHANGELOG.md
Cargo.toml
SECURITY.md

Add CHANGELOG.md and SECURITY.md + bump version number.
Signed-off-by: Davide Bettio <davide.bettio@secomind.com>

Prepare v0.5.0 release

---

CHANGELOG.md

Signed-off-by: Davide Bettio <davide.bettio@secomind.com>

Update v0.5.0 release date to 2022-10-10

---

src/ota/ota_handler.rs

The OTA update file is left on the disk after the OTA update even if it is not needed anymore.
In addition to removing the file after the installation, an additional check is performed on the eventually existing file before downloading.

Remove update file after installation

---

CHANGELOG.md
Cargo.toml

Prepare release 0.6.0

---

CHANGELOG.md

Update the formatting of the changelog to comply with the "Keep a Changelog" guidelines.

Update Changelog formatting

---

Cargo.lock

Update runtime version in cargo lock

---

.github/workflows/check.yaml
.github/workflows/codecov.yaml
.github/workflows/e2e-test.yaml
.github/workflows/test.yaml
src/lib.rs
src/ota/ota_handle.rs
src/telemetry/mod.rs

Check all features and targets not permitting warnings

feat(ci): improve the ci workflows

---

.reuse/dep5
Cargo.lock
Cargo.toml
edgehog-device-runtime-docker/CHANGELOG.md
edgehog-device-runtime-docker/Cargo.toml
edgehog-device-runtime-docker/README.md
edgehog-device-runtime-docker/src/client.rs
edgehog-device-runtime-docker/src/docker.rs
edgehog-device-runtime-docker/src/error.rs
edgehog-device-runtime-docker/src/lib.rs
edgehog-device-runtime-docker/src/mock.rs
hardware-id-service/src/main.rs

Add the docker package to the workspace and the dependencies.
Closes #211

feat(docker): add docker package to the workspace

---

README.md
src/ota/ota_handle.rs
src/ota/ota_handler.rs
src/ota/ota_handler_test.rs
src/ota/rauc.rs
src/telemetry/mod.rs
src/telemetry/os_info.rs

This PR also fixes some typos in the code

refactor(mock): keep the owned value and remove the &

---

Cargo.lock
edgehog-device-runtime-docker/src/mock.rs
src/telemetry/net_if_properties.rs

Fix warning for the new clippy version in the latest nightly.

fix(clippy): fix warnings introduced by new clippy version

---

src/lib.rs
src/telemetry/mod.rs
src/telemetry/storage_usage.rs

This should temporarily provide a solution to the second point explained in #232

fix(storage): remove disks with a depth higher than /dev

---

Cargo.lock
hardware-id-service/Cargo.toml
hardware-id-service/scripts/get-hardware-id.sh
hardware-id-service/src/main.rs
led-manager-service/Cargo.toml
led-manager-service/README.md
led-manager-service/scripts/insert.sh
led-manager-service/scripts/list.sh
led-manager-service/scripts/set.sh
led-manager-service/src/main.rs

Move the services to stable-eyre and tracing. Remove the unwraps and
gather the information beforehand when starting the services.z

refactor(services): update the dbus services

---

edgehog-device-runtime-containers/src/docker/mod.rs
edgehog-device-runtime-containers/src/docker/volume.rs
edgehog-device-runtime-containers/src/error.rs
edgehog-device-runtime-containers/src/properties/mod.rs
edgehog-device-runtime-containers/src/properties/volume.rs
edgehog-device-runtime-containers/src/requests/mod.rs
edgehog-device-runtime-containers/src/requests/volume.rs
edgehog-device-runtime-containers/src/service/mod.rs
edgehog-device-runtime-containers/src/service/resource.rs
edgehog-device-runtime-containers/src/store/mod.rs
edgehog-device-runtime-containers/src/store/volume.rs

feat(docker): create volume req

---

edgehog-device-runtime-containers/src/docker/mod.rs
edgehog-device-runtime-containers/src/docker/network.rs
edgehog-device-runtime-containers/src/error.rs
edgehog-device-runtime-containers/src/properties/mod.rs
edgehog-device-runtime-containers/src/properties/network.rs
edgehog-device-runtime-containers/src/requests/mod.rs
edgehog-device-runtime-containers/src/requests/network.rs
edgehog-device-runtime-containers/src/service/mod.rs
edgehog-device-runtime-containers/src/service/resource.rs
edgehog-device-runtime-containers/src/store/mod.rs
edgehog-device-runtime-containers/src/store/network.rs

feat(docker): create network req

---

Cargo.lock
Cargo.toml
src/commands.rs
src/controller/event.rs
src/controller/mod.rs
src/data/astarte_device_sdk_lib.rs
src/error.rs
src/lib.rs
src/ota/mod.rs
src/ota/ota_handler.rs
src/ota/rauc.rs
src/telemetry/mod.rs
src/telemetry/sender.rs

Moved ota, udev and wifiscanner to optional features

---

Cargo.lock
Cargo.toml
e2e-test-containers/assets/data.json
e2e-test-containers/src/main.rs
e2e-test-containers/src/send.rs
edgehog-device-runtime-containers/Cargo.toml
edgehog-device-runtime-containers/src/docker/container.rs
edgehog-device-runtime-containers/src/docker/mod.rs
edgehog-device-runtime-containers/src/error.rs
edgehog-device-runtime-containers/src/properties/container.rs
edgehog-device-runtime-containers/src/properties/mod.rs
edgehog-device-runtime-containers/src/requests/container.rs
edgehog-device-runtime-containers/src/requests/mod.rs
edgehog-device-runtime-containers/src/service/collection.rs
edgehog-device-runtime-containers/src/service/mod.rs
edgehog-device-runtime-containers/src/service/node.rs
edgehog-device-runtime-containers/src/service/resource.rs
edgehog-device-runtime-containers/src/service/state.rs
edgehog-device-runtime-containers/src/store/container.rs
edgehog-device-runtime-containers/src/store/mod.rs

feat(docker): create container req

---

Cargo.lock
e2e-test-containers/src/receive.rs
edgehog-device-runtime-containers/Cargo.toml
edgehog-device-runtime-containers/src/events.rs
edgehog-device-runtime-containers/src/properties/container.rs
edgehog-device-runtime-containers/src/properties/deployment.rs
edgehog-device-runtime-containers/src/properties/image.rs
edgehog-device-runtime-containers/src/properties/mod.rs
edgehog-device-runtime-containers/src/properties/network.rs
edgehog-device-runtime-containers/src/properties/volume.rs
edgehog-device-runtime-containers/src/requests/container.rs
edgehog-device-runtime-containers/src/requests/image.rs
edgehog-device-runtime-containers/src/requests/network.rs
edgehog-device-runtime-containers/src/requests/volume.rs
edgehog-device-runtime-containers/src/service/collection.rs
edgehog-device-runtime-containers/src/service/mod.rs
edgehog-device-runtime-containers/src/service/node.rs
edgehog-device-runtime-containers/src/service/resource.rs
edgehog-device-runtime-containers/src/service/state.rs
edgehog-device-runtime-containers/src/store/mod.rs

- Tag the container resource Id with the resource type
- Make the string part of the Id a UUID

refactor(container): improve the Resource Id

---

Cargo.lock
Cargo.toml
e2e-test-containers/assets/data.json
e2e-test-containers/assets/stop.json
e2e-test-containers/src/receive.rs
edgehog-device-runtime-containers/Cargo.toml
edgehog-device-runtime-containers/src/requests/container.rs
edgehog-device-runtime-containers/src/requests/deployment.rs
edgehog-device-runtime-containers/src/requests/image.rs
edgehog-device-runtime-containers/src/requests/mod.rs
edgehog-device-runtime-containers/src/requests/network.rs
edgehog-device-runtime-containers/src/requests/volume.rs
edgehog-device-runtime-containers/src/service/mod.rs
edgehog-device-runtime-containers/src/store/mod.rs
src/containers.rs
src/controller/event.rs
src/controller/mod.rs
src/data/mod.rs
src/error.rs
src/lib.rs

Create a task to handle the container requests and commands from
Astarte.

feat(containers): integrate the with the runtime

---

e2e-test-containers/assets/update.json
edgehog-device-runtime-containers/src/docker/container.rs
edgehog-device-runtime-containers/src/events.rs
edgehog-device-runtime-containers/src/requests/deployment.rs
edgehog-device-runtime-containers/src/requests/mod.rs
edgehog-device-runtime-containers/src/service/collection.rs
edgehog-device-runtime-containers/src/service/mod.rs
src/containers.rs

Add the interface to update from a deployment to another one.

feature(container): update between two deployments

---

src/data/astarte_device_sdk_lib.rs
src/main.rs
src/ota/mod.rs
src/ota/ota_handler.rs
src/telemetry/mod.rs

Fix task error report

---

edgehog-device-runtime-containers/src/docker/image.rs
edgehog-device-runtime-containers/src/service/collection.rs
edgehog-device-runtime-containers/src/service/mod.rs
edgehog-device-runtime-containers/src/service/node.rs

Add the resource to previously added missing nodes.

fix(container): correctly check node existence

---

edgehog-device-runtime-containers/src/service/collection.rs
edgehog-device-runtime-containers/src/service/mod.rs
edgehog-device-runtime-containers/src/service/resource.rs

When restarting, filter the running deployment and make sure they are
started.

feat(containers): auto start container in up state

---

Cargo.lock
Cargo.toml
edgehog-device-runtime-containers/Cargo.toml
edgehog-device-runtime-containers/src/docker/image.rs
edgehog-device-runtime-containers/src/docker/network.rs
edgehog-device-runtime-containers/src/docker/volume.rs
edgehog-device-runtime-containers/src/properties/mod.rs
edgehog-device-runtime-containers/src/requests/deployment.rs
edgehog-device-runtime-containers/src/service/collection.rs
edgehog-device-runtime-containers/src/service/mod.rs
edgehog-device-runtime-containers/src/service/node.rs

Fetch the status on restart before starting the containers.

feat(container): fetch status on restart

---

README.md
e2e-test-containers/src/receive.rs
e2e-test/Cargo.toml
e2e-test/src/main.rs
edgehog-device-runtime-containers/src/docker/container.rs
edgehog-device-runtime-containers/src/docker/image.rs
edgehog-device-runtime-containers/src/docker/network.rs
edgehog-device-runtime-containers/src/docker/volume.rs
edgehog-device-runtime-containers/src/events.rs
edgehog-device-runtime-containers/src/properties/mod.rs
edgehog-device-runtime-containers/src/requests/deployment.rs
edgehog-device-runtime-containers/src/service/collection.rs
edgehog-device-runtime-containers/src/service/mod.rs
src/config.rs
src/containers.rs
src/controller/actor.rs
src/controller/mod.rs
src/lib.rs
src/ota/ota_handler.rs
src/telemetry/mod.rs

Make the container service configurable and implement better logging and
handling of error in the whole runtime.

feat(containers): add config and better error handling

---

e2e-test-containers/assets/data.json
e2e-test-containers/assets/isolate-no-net.json
e2e-test-containers/assets/update.json
edgehog-device-runtime-containers/src/requests/container.rs
edgehog-device-runtime-containers/src/requests/image.rs
edgehog-device-runtime-containers/src/requests/mod.rs
edgehog-device-runtime-containers/src/requests/network.rs
edgehog-device-runtime-containers/src/requests/volume.rs
edgehog-device-runtime-containers/src/service/events.rs
edgehog-device-runtime-containers/src/service/mod.rs
edgehog-device-runtime-containers/src/store/container.rs
edgehog-device-runtime-containers/src/store/deployment.rs
edgehog-device-runtime-containers/src/store/image.rs
edgehog-device-runtime-containers/src/store/mod.rs
edgehog-device-runtime-containers/src/store/network.rs
edgehog-device-runtime-containers/src/store/volume.rs
src/lib.rs

refactor(container): update the structs for the new interfaces

---

edgehog-device-runtime-containers/src/docker/container.rs
edgehog-device-runtime-containers/src/docker/image.rs
edgehog-device-runtime-containers/src/docker/network.rs

When a resource with the given id is not found, check for the name
instead.

feat(containers): make inspect more robust

---

.github/workflows/check.yaml
CHANGELOG.md
Cargo.lock
Cargo.toml
cellular-modems-service/src/main.rs
doc/os_requirements.md
e2e-test-containers/Cargo.toml
e2e-test/Cargo.toml
edgehog-device-runtime-containers/Cargo.toml
edgehog-device-runtime-forwarder/Cargo.toml
edgehog-device-runtime-forwarder/src/connections_manager.rs
edgehog-device-runtime-forwarder/src/messages.rs
edgehog-device-runtime-forwarder/tests/http_test.rs
edgehog-device-runtime-forwarder/tests/ws_test.rs
hardware-id-service/src/main.rs
led-manager-service/src/main.rs
src/device.rs
src/led_behavior.rs
src/main.rs
src/ota/mod.rs
src/ota/rauc.rs
src/telemetry/cellular_properties.rs
src/telemetry/upower/device.rs
src/telemetry/upower/mod.rs

Update the dependency major versions.

refactor(msrv): bump the MSRV to 1.78

---

scripts/coverage.sh

Remove target directory to prevent codecov to upload the profraw files.

ci(coverage): fix coverage script
