- src/lib.rs
Publish data to `/systemStatus` instead of `/systemStatus/`.
> Make it work with latest Astarte SDK version

- Cargo.lock
- Cargo.toml
- README.md
- src/lib.rs
- src/telemetry/mod.rs
- src/telemetry/runtime_info.rs
closes #5 
`/environment` is statically set to "Rust" since there's no standard way to get the compiler version for a rust program
> Implement io.edgehog.devicemanager.RuntimeInfo

- README.md
- doc/os_requirements.md
Add OS requirements in order to make Edgehog Device Runtime easier to integrate.
> Add OS requirements doc

- src/telemetry/system_status.rs
Add boot_id to SystemStatus using `/proc/sys/kernel/random/boot_id`
Closes #13
> Add boot_id to SystemStatus

- Cargo.lock
- src/commands.rs
- src/lib.rs
- src/ota_handler.rs
- src/power_management.rs
Implement `io.edgehog.devicemanager.Commands`
The new server owned interface is added with an improved selector for incoming data, removing the nested ifs that were there before
closes #19
> Implement io.edgehog.devicemanager.Commands

- src/telemetry/os_info.rs
- Check the behaviour if os_release contains an empty line in the middle.
- Check the behaviour if os_release contains only the os_name.
- Check the behaviour if os_release file is malformed.
- Split parse_os_info function.
- Separate key_value parsing from osName and osVersion.
- Add tests to parse_key_value line function.
> Add tests to os_info

- Cargo.lock
- Cargo.toml
- README.md
- src/config.rs
- src/error.rs
- src/lib.rs
- src/main.rs
- src/ota_handler.rs
Add toml configuration file, for example:
```
/etc/edgehog.conf
```
```toml
credentials_secret = "xxxxx"
device_id = "xxxxx"
pairing_url = "https://api.xxxxx/pairing"  
realm = "xxxxx"
interfaces_directory = "/var/lib/xxxx"
state_file = "/xxxx/xx"
download_directory = "/tmp"
```
> Make it configurable

- .github/workflows/build.yaml
Add `1.59.0` as target of the `rust-toolchain` in the `build` GitHub
workflow.
> Add 1.59.0 rust version as CI target

- Cargo.lock
- Cargo.toml
- README.md
- src/lib.rs
- src/main.rs
- src/wrapper/mod.rs
- src/wrapper/systemd.rs
Add rust-systemd as optional library
- Notify service manager about Device Runtime status changes
- Create an initial wrapper around `rust-systemd` crate because not all systems support systemd.
- Register a custom panic hook for sending `PanicInfo` to systemd status.
> Add systemd library

- src/lib.rs
- src/ota_handler.rs
- src/repository/file_state_repository.rs
- src/repository/mod.rs
Repositories encapsulate the logic required to access data sources.
They centralize common data access functionality, providing better maintainability and decoupling the infrastructure or technology
used to access the data.
> Add Repository for saving Runtime State

- .github/workflows/codecov.yaml
- codecov.yml
- src/lib.rs
- src/main.rs
- src/repository/file_state_repository.rs
- src/repository/mod.rs
- src/telemetry/hardware_info.rs
- Change Codecov settings by adding the `--lib` flag to test only this package library and adding the `--ignore-tests` flag to avoid including test functions themselves in the coverage lines count.
- Add tests in various files to improve coverage.
- Remove some functions from coverage count.
> Improve test coverage

- hardware-id-service/io.edgehog.Device.conf
- hardware-id-service/src/main.rs
Copying the config onto `/etc/dbus-1/system.d/` with the current license comment makes it unreadable by dbus.
Change the comment to be XML compliant.
Remove extra space in a parameter name.
> Fix hardware-id-service dbus config file and use-dmi-serial handling

- .github/workflows/build.yaml
Sometimes test builds return some `unused import` or `unused variable` warning because some code parts are not used or mocked during tests.
These warnings are then reported as annotations in the `Files changed` tab disturbing the review process.
The Rust flag `-Awarning` suppresses this behavior during `cargo test`.
> Disable Warning annotations on test builds

- src/ota/mod.rs
- src/ota/ota_handler.rs
- src/ota/rauc.rs
Normally, the full system update chain is not complete before being sure that the newly installed system runs without any errors.
As the definition and detection of a successful operation is really  system-dependent, so we need to inform the bootloader that the slot selected by it was good.
> RAUC mark slot as good

- Cargo.lock
- Cargo.toml
- src/data/mod.rs
- src/ota/mod.rs
- src/repository/mod.rs
Typically mockall is only used by unit tests.
> Use mockall only as dev-dependencies

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/main.rs
- src/ota/ota_handler.rs
- src/repository/file_state_repository.rs
- Introduce a directory for data storage so that all data are confined to the same location and do not have files scattered throughout the system.
- Check configured path before device-runtime starts.
- Add some tests on get_credentials function.
> Remove single file storage

- .github/workflows/e2e-test.yaml
- Cargo.toml
- src/e2e_test/e2e_test.rs
- src/lib.rs
Add e2e_test public module for exposing as public API the private telemetry function, in order to collect and validate the data sent from the Device Runtime to Astarte.This was enabled only If the Device Runtime will be executed with the feature `e2e_test` enabled.
``` shell 
cargo run --bin e2etest --features e2e_test
```
Add os_info, hardware_info and runtime_info validation tests.
> Add end to end test

- Cargo.toml
- README.md
- Since the binary of `e2e-test` has been added, it should also be added which is the default binary, otherwise `cargo run` could not determine which binary to run.
- Update example configuration.
> Specify default-run binary

- Cargo.lock
- Cargo.toml
- src/telemetry/system_status.rs
-  The `all_processes` function doesn't return a Vec but an Iterator and since It isn't an `ExactSizeIterator` we can't use `len` function anymore, but we should use the `count` function.
- Add test to check that I didn't break the collection of system status.
> Bump procfs from 0.12.0 to 0.13.2

- src/lib.rs
- src/main.rs
This allows Edgehog-Device-Runtime to be connected to an instance of Astarte that doesn't have ssl configured.
Closes #103.
> Add ignore ssl option for configuring Astarte-SDK

- Cargo.lock
- Cargo.toml
- src/telemetry/hardware_info.rs
- Use `std::env::consts::ARCH` for reading the architecture of the CPU
- Remove `nix` crate dependency
> Use consts::ARCH for reading the architecture of the CPU

- src/lib.rs
- src/telemetry/mod.rs
- src/telemetry/system_info.rs
Add `io.edgehog.devicemanager.SystemInfo` to `send_initial_telemetry`
with data fetched from the kernel cmdline and from ENV variables.
Close #9
> System Info support

- src/data/astarte.rs
- src/data/mod.rs
- src/e2e_test/e2e_test.rs
- src/lib.rs
- src/main.rs
- Avoid blocking main loop, all data received from Astarte will be passed through a channel.
- For the OTA event, we use a dedicated channel with buffer capacity equal to 1 because it can only receive one OTA event at a time.
-  Inject Astarte Device as dependecy to the DeviceManager.
- Use Publisher trait on DeviceManager struct is useful both for not depending directly on the SDK and for testing reasons.
- Move Astarte stuffs in data module.
- Add tests
> Device Manager new function refactoring

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/lib.rs
- src/telemetry/mod.rs
- src/telemetry/wifi_scan.rs
Add the Wi-Fi scan functionality using `iw` on Linux via the
`wifiscanner` rust crate.
Close #24 
> Add support to WiFiScanResults

- .github/workflows/build.yaml
- src/data/astarte.rs
- src/e2e_test/e2e_test.rs
- src/lib.rs
- src/telemetry/mod.rs
- Add support to `io.edgehog.devicemanager.config.Telemetry`
- Add `telemetry_config` as an array of mappings in the `edgehog_config.toml` to represent the default telemetry configs.
Close #11
> Implement io.edgehog.devicemanager.config.Telemetry

- README.md
- doc/os_requirements.md
- src/lib.rs
- src/telemetry/base_image.rs
- src/telemetry/mod.rs
Add support retrieving `IMAGE_ID` AND `IMAGE_VERSION` from `/etc/os-release` for `io.edgehog.devicemanager.BaseImage`. 
Said data are optional and limited to supported OSs. 
`/name` is retrieved from `IMAGE_ID`;
`/version` is retrieved from the first half of `IMAGE_VERSION` splitted over the character `+`;
`/buildId` is retrieved from the first half of `IMAGE_VERSION` splitted over the character `+`;
`/fingerprint` is left for future releases and only for OSs supporting image hashing.
Close #6 
> Add support to BaseImage

- src/data/astarte.rs
- src/error.rs
Before this change, the internal error was lost, so it made difficult to identify the actual problem.
> Display actual error message in DeviceManagerError

- README.md
- src/data/astarte.rs
- src/e2e_test/e2e_test.rs
- src/lib.rs
- src/telemetry/mod.rs
Update `DeviceManagerOptions` to make `telemetry_config` optional. 
Update the README to show the `telemetry_config`setup.
> Make `telemetry_config` optional

- README.md
- doc/os_requirements.md
- src/lib.rs
- src/telemetry/battery_status.rs
- src/telemetry/mod.rs
- src/telemetry/upower/device.rs
- src/telemetry/upower/mod.rs
- src/telemetry/upower/upower.rs
Add support to `io.edgehog.devicemanager.BatteryStatus` interface
with data from UPower collected via D-Bus.
Close #16 
> Implement io.edgehog.devicemanager.BatteryStatus

- .github/workflows/build.yaml
- Cargo.toml
This is revert is required in order to support older Rust version used on buildroot.
> Revert sysinfo to 0.26.2

- src/data/astarte.rs
At this moment `device_id` and `credentials_secret` read from the configuration directly, without checking if it's not empty. 
Add a check to ignore empty strings
Close #153 
> Handle empty `device_id` and `credentials_secret` in configuration

- .github/workflows/check.yaml
- .github/workflows/codecov.yaml
- .github/workflows/e2e-test.yaml
- .github/workflows/test.yaml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- README.md
- src/data/astarte_device_sdk_lib.rs
- src/data/astarte_message_hub_node.rs
- src/data/mod.rs
- src/e2e_test/e2e_test.rs
- src/error.rs
- src/lib.rs
- src/main.rs
~~In the AstarteMessageHubNode struct I used a Mutex instead of RwLock, because the tonic::transport::Streaming is !Sync so it can be shared between threads only using a Mutex (this is an interesting difference between the two).~~
- Separate Astarte Subscriber from Publisher.
- Add Protoc install to CI.
closes #169
> Add Astarte Message Hub

- .github/dependabot.yml
The minor and patch updates are worth it for this project since it is a binary. It was my mistake for previously adding the ignore.
> fix(dependabot): remove the ignore since this is a binary

- .gitignore
- Cargo.lock
- Cargo.toml
- hardware-id-service/Cargo.toml
Since it's hard to work with the MSRV this PR is to pin the transitive dependencies to the one working with the MSRV. This makes it easier to add, remove or update dependencies without breaking the build.
> chore(deps): pin dependencies to work with MSRV

- src/ota/mod.rs
- src/ota/ota_handle.rs
- src/ota/ota_handler.rs
- src/ota/ota_handler_test.rs
- src/ota/rauc.rs
- src/power_management.rs
Remove the delays and channels from the tests. Replace the test that require to receive a channel as "expect" and make it return a progress stream directly.
> feat(ota): improve tests and make the progress a stream

- src/ota/ota_handle.rs
- src/ota/ota_handler_test.rs
- src/telemetry/battery_status.rs
The test update after cancel would fail since it asserted that two to download by the server. The two calls would only happen in a specific sequence of messages exchanged by the channels between the `ota` and `ota_handle` tasks. Sometimes the cancel message arrived before the file was downloaded, and the assertion of two hits on the mock server would fail. The change takes in consideration this by or-ing the two cases, it also improves the tempdir creation by providing a prefix for each test.
> fix(test): racy assertion in test update after cancel

- e2e-test/src/main.rs
- src/data/astarte_device_sdk_lib.rs
- src/data/astarte_message_hub_node.rs
- src/lib.rs
- src/main.rs
- src/ota/ota_handle.rs
- src/ota/ota_handler.rs
- src/repository/file_state_repository.rs
- src/telemetry/mod.rs
Use the `Path{Buf}` struct instead of strings to simplify the code.
> refactor(path): use path instead of string

- .reuse/dep5
- Cargo.lock
- Cargo.toml
- edgehog-device-runtime-docker/src/mock.rs
- edgehog-device-runtime-forwarder/Cargo.toml
- edgehog-device-runtime-forwarder/README.md
- edgehog-device-runtime-forwarder/src/astarte.rs
- edgehog-device-runtime-forwarder/src/connections_manager.rs
- edgehog-device-runtime-forwarder/src/lib.rs
- edgehog-device-runtime-forwarder/src/tls.rs
- edgehog-device-runtime-forwarder/tests/http_test.rs
- src/data/astarte_message_hub_node.rs
- src/forwarder.rs
Implementation of a secure WebSocket communication with Edgehog.
By setting the `EDGEHOG_FORWARDER_CA_PATH` environment variable it is possible to install a custom CA certificate in
the root certificate store, which is useful in the case of testing on localhost.
additional changes:
- update the name of the interfaces to handle forwarder sessions state and requests
- changed `disconnected` to `unset`
> feat(wss): implement TLS layer for WSS

- .gitignore
- Cargo.lock
- Cargo.toml
- e2e-test-forwarder/Cargo.toml
- e2e-test-forwarder/src/main.rs
- edgehog-device-runtime-forwarder/Cargo.toml
- edgehog-device-runtime-forwarder/README.md
- edgehog-device-runtime-forwarder/src/astarte.rs
- edgehog-device-runtime-forwarder/src/collection.rs
- edgehog-device-runtime-forwarder/src/connection.rs
- edgehog-device-runtime-forwarder/src/connection/http.rs
- edgehog-device-runtime-forwarder/src/connection/mod.rs
- edgehog-device-runtime-forwarder/src/connection/websocket.rs
- edgehog-device-runtime-forwarder/src/connections_manager.rs
- edgehog-device-runtime-forwarder/src/lib.rs
- edgehog-device-runtime-forwarder/src/messages.rs
- edgehog-device-runtime-forwarder/src/test_utils.rs
- edgehog-device-runtime-forwarder/src/tls.rs
- edgehog-device-runtime-forwarder/tests/http_test.rs
- edgehog-device-runtime-forwarder/tests/ws_test.rs
We would like to establish one or more WebSocket connections on top of
an existing WebSocket channel between a device and a bridge. For
instance, this could be useful in the scenario where a remote user, who
has access to the bridge, wishes to open a remote terminal exposed by
the device on a specific port and make it accessible through a WebSocket
connection.  The implementation of this functionality is described as
follows:
- `edgehog-device-runtime-forwarder/src/messages.rs` has been extended
to reflect the changes in the `proto.rs` file, which contains the
[`Protobuf`](https://protobuf.dev/) definition of the data exchanged
between the device and the bridge. Since this extension introduces the
WebSocket message type, now `messages.rs` contains the necessary structs
and `impl` blocks …
> feat(ws): implement websocket over websocket

- .github/workflows/ci.yaml
Since the hosted DCO app is currently down we will use a forked version, implemented as a Github Action. This is a temporary fix until the projects resolves the hosting issues.
> refactor(ci): use custom DCO action

- Cargo.lock
- Cargo.toml
- e2e-test/Cargo.toml
- edgehog-device-runtime-forwarder/Cargo.toml
- edgehog-device-runtime-forwarder/src/test_utils.rs
- edgehog-device-runtime-forwarder/tests/ws_test.rs
- src/data/astarte_message_hub_node.rs
- src/telemetry/storage_usage.rs
Update to latest version. Fix a new error in the forwarder test which requires the Sec-WebSocket-Protocol headers to be present in the mock server response. Remove unused features for the runtime e2e-test.
> chore(deps): update major version of the deps

- src/ota/ota_handler_test.rs
- src/ota/rauc.rs
- src/telemetry/mod.rs
Elide lifetimes when possible and use is_empty instead of `.eq("")`
> fix(clippy): solve some warnings

- Cargo.lock
- Cargo.toml
- edgehog-device-runtime-containers/Cargo.toml
- edgehog-device-runtime-containers/src/docker/image.rs
- edgehog-device-runtime-containers/src/docker/mod.rs
- edgehog-device-runtime-containers/src/error.rs
- edgehog-device-runtime-containers/src/lib.rs
- edgehog-device-runtime-containers/src/properties/image.rs
- edgehog-device-runtime-containers/src/properties/mod.rs
- edgehog-device-runtime-containers/src/requests/image.rs
- edgehog-device-runtime-containers/src/requests/mod.rs
- edgehog-device-runtime-containers/src/service/collection.rs
- edgehog-device-runtime-containers/src/service/mod.rs
- edgehog-device-runtime-containers/src/service/node.rs
- edgehog-device-runtime-containers/src/service/resource.rs
- edgehog-device-runtime-containers/src/service/state.rs
- edgehog-device-runtime-containers/src/store/image.rs
- edgehog-device-runtime-containers/src/store/mod.rs
> feat(docker): create image req

- Cargo.lock
- Cargo.toml
- edgehog-device-runtime-forwarder/Cargo.toml
- src/main.rs
Since we can have different versions of rustls, we decide to install ring as default provider to avoid the `no crypto provider install` issue generated by two different version of rustls used by the application.
> Use ring as default crypto provider

- REUSE.toml
- e2e-test-containers/assets/stop.json
- e2e-test-containers/src/receive.rs
- edgehog-device-runtime-containers/src/docker/container.rs
- edgehog-device-runtime-containers/src/events.rs
- edgehog-device-runtime-containers/src/properties/container.rs
- edgehog-device-runtime-containers/src/service/collection.rs
- edgehog-device-runtime-containers/src/service/mod.rs
- edgehog-device-runtime-containers/src/service/node.rs
- edgehog-device-runtime-containers/src/service/resource.rs
- edgehog-device-runtime-containers/src/service/state.rs
Implement the stop for the deployment that will stop all the container
in the deployment. It will skip containers used in other deployments.
> feat(containers): add stop for the deployment

- edgehog-device-runtime-containers/src/service/mod.rs
- edgehog-device-runtime-containers/src/service/node.rs
- edgehog-device-runtime-containers/src/service/resource.rs
- edgehog-device-runtime-containers/src/store/mod.rs
This removes some warnings on restart, when the resources are loaded with state stored.
Now they are loaded with the actual state.
> refactor(state): store the resource state

- e2e-test-containers/assets/data.json
- e2e-test-containers/assets/update.json
- edgehog-device-runtime-containers/src/docker/mod.rs
- edgehog-device-runtime-containers/src/events.rs
- edgehog-device-runtime-containers/src/requests/container.rs
- edgehog-device-runtime-containers/src/service/collection.rs
- edgehog-device-runtime-containers/src/service/mod.rs
Revert the order of the resource visited so they can be deleted
correctly. We need to delete the containers before the images, etc.
> fix(container): order container to delete 

- src/main.rs
Enable ansi codes only if the stdout is a terminal.
> fix(tracing): check if stdout is a terminal

- edgehog-device-runtime-containers/src/service/collection.rs
Traverse the graph correctly so we don't have incorrect dependencies.
> fix(store): get the correct dependencies 

- Cargo.toml
Strip the release executable and create a separated, full and packed
debug symbols.
> feat(release): strip and separate debug symbols 

- edgehog-device-runtime-containers/src/docker/container.rs
- edgehog-device-runtime-containers/src/requests/container.rs
- edgehog-device-runtime-containers/src/requests/deployment.rs
- edgehog-device-runtime-containers/src/requests/image.rs
- edgehog-device-runtime-containers/src/requests/mod.rs
- edgehog-device-runtime-containers/src/requests/network.rs
- edgehog-device-runtime-containers/src/requests/volume.rs
- edgehog-device-runtime-containers/src/service/mod.rs
Parse the uuid when converting the event.
> feat(container): use uuid instead of strings

- doc/os_requirements.md
This specifies access to the socket that should be used to listen for notifications when the “notify” service type is selected.
> doc: Add NotifyAccess option to system section

- .github/workflows/check.yaml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- e2e-test/src/main.rs
- edgehog-device-runtime-forwarder/src/astarte.rs
- edgehog-device-runtime-forwarder/src/connections_manager.rs
- src/data/astarte_device_sdk_lib.rs
- src/data/astarte_message_hub_node.rs
- src/data/mod.rs
- src/forwarder.rs
- src/lib.rs
- src/main.rs
- src/ota/ota_handler_test.rs
- src/ota/rauc.rs
- src/telemetry/mod.rs
This will make it possible to connect to newer versions of the msg hub.
> chore(deps): bump the astarte-device-sdk to v0.8

- .github/workflows/test.yaml
- scripts/coverage.sh
- src/containers.rs
- src/controller/mod.rs
- src/lib.rs
Enable branch coverage and use rustc directly for the coverage. This simplifies the compilation step that had failed often with cargo-tarpaulin.
> ci(coverage): use grcov to generate a report

- .github/codecov.yaml
Separate the configuration in components. Do not error in main branch if
status is lowered.
> ci(codevov): add components to config 

- .github/workflows/check.yaml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- doc/os_requirements.md
- e2e-test/src/main.rs
- edgehog-device-runtime-containers/CHANGELOG.md
- edgehog-device-runtime-containers/src/docker/network.rs
- edgehog-device-runtime-forwarder/src/connection/mod.rs
- edgehog-device-runtime-forwarder/src/connection/websocket.rs
- edgehog-device-runtime-forwarder/src/connections_manager.rs
- edgehog-device-runtime-forwarder/src/messages.rs
- edgehog-device-runtime-forwarder/src/test_utils.rs
- edgehog-device-runtime-forwarder/tests/http_test.rs
- edgehog-device-runtime-forwarder/tests/ws_test.rs
- src/data/astarte_device_sdk_lib.rs
- src/data/astarte_message_hub_node.rs
- src/forwarder.rs
- src/lib.rs
- src/main.rs
- src/telemetry/mod.rs
Forward port the changes in the release-0.9 branch before merging feature-containers into it.
Bump all the dependencies to the latest version.
> chore(forward): port release 0.9

- src/ota/mod.rs
- src/ota/ota_handler.rs
- src/ota/ota_handler_test.rs
- src/ota/rauc.rs
Use RAUC to download the OTA using the HTTP streaming mode.
> refactor(ota): remove the download from the OTA state machine

- Cargo.toml
This achieves similar performance while taking substantial less time.
> chore(release): use "thin" instead of "fat" lto

- src/ota/mod.rs
- src/ota/ota_handler_test.rs
- src/ota/rauc.rs
Remove the direct reboot command and add a signal to the RAUC interface to wait and signal reboot errors to the device runtime.
> feat(reboot): add custom reboot

- edgehog-device-runtime-containers/src/events/deployment.rs
- edgehog-device-runtime-containers/src/resource/mod.rs
- edgehog-device-runtime-containers/src/service/mod.rs
Add the Started and Stopped statuses to the deployment event. This will
send a datastream with a timestamp in addition to setting the Started
state of the property.
The DatastreamEvent is an `explicit_timestamp`, so we use the sender
timestamp and not the reception one.
> feat(containers): add DeploymentEvent Started and Stopped 
